//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Peregrinus.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UninstallMigrationCmdletTranslations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UninstallMigrationCmdletTranslations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Peregrinus.Resources.UninstallMigrationCmdletTranslations", typeof(UninstallMigrationCmdletTranslations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value for the -Count parameter. Please specify a positive integer..
        /// </summary>
        internal static string InvalidCountParameterExceptionMessage {
            get {
                return ResourceManager.GetString("InvalidCountParameterExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value for the -TargetVersion parameter. Make sure the specified value follows semver rules. See https://semver.org.
        /// </summary>
        internal static string InvalidTargetVersionParameterExceptionMessage {
            get {
                return ResourceManager.GetString("InvalidTargetVersionParameterExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollback.
        /// </summary>
        internal static string RollbackByStrategyResultActivity {
            get {
                return ResourceManager.GetString("RollbackByStrategyResultActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollback complete..
        /// </summary>
        internal static string RollbackByStrategyResultDescription {
            get {
                return ResourceManager.GetString("RollbackByStrategyResultDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollback {0}.
        /// </summary>
        internal static string RollbackSingleResultActivity {
            get {
                return ResourceManager.GetString("RollbackSingleResultActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: migration was rolled back..
        /// </summary>
        internal static string RollbackSingleResultDescription {
            get {
                return ResourceManager.GetString("RollbackSingleResultDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one strategic parameter was specified. Use one of either -Count, -TargetVersion or -All parameters..
        /// </summary>
        internal static string StrategicParametersCountExceptionMessage {
            get {
                return ResourceManager.GetString("StrategicParametersCountExceptionMessage", resourceCulture);
            }
        }
    }
}
